package com.rofour.baseball.dao.order.bean;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class OrderManagerBean implements Serializable{
    private static final long serialVersionUID = 8550080699642155028L;
	/**
     * 小派userId
     */
    private Long userId;
	/**
     * 打赏金额
     */
    private Long rewardMoney;

    private String serviceType = "快递";
    /**
     * 运单号
     */
    private String waybillNo;
	/**
     * 寄件取货码
     */
    private String pickUpCode;
	/**
     * 代取件取货码
     */
    private String agentPickupCode;
	/**
     * 订单流转记录
     */
    private List<OrderFlowBean> orderFlowList;
	/**
	 * 城市名称
     */
    private String cityName;
	/**
     * 校区名称
     */
    private String collegeName;
	/**
     * 接单人(小派)手机号
     */
    private String winnerMobile;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.order_id
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.source
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.channel
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.TYPE
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.total_money
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private Long totalMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.rebate_money
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private Long rebateMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.final_money
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private Long finalMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.state
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.pay_money
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private Long payMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.pay_state
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private Integer payState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.pay_type
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.pay_id
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private Long payId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.cancel_type
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private Integer cancelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.consignee
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private String consignee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.address
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.delivery_start_date
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private Date deliveryStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.delivery_end_date
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private Date deliveryEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.create_user
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.create_user_mobile
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private String createUserMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.mobile
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.remark
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.unnormal_desc
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private String unnormalDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.create_date
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.update_user
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private Long updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.update_date
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.sex
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.pay_mode
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private Integer payMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.lock_state
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private Integer lockState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.trader
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private String trader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.trader_name
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private String traderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.trader_sex
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private String traderSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.trader_mobile
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private String traderMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.trader_address
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private String traderAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.winner
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private Long winner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.winner_remark
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private String winnerRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.college_id
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    private Long collegeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.order_id
     *
     * @return the value of tb_order.order_id
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.order_id
     *
     * @param orderId the value for tb_order.order_id
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.source
     *
     * @return the value of tb_order.source
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.source
     *
     * @param source the value for tb_order.source
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.channel
     *
     * @return the value of tb_order.channel
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.channel
     *
     * @param channel the value for tb_order.channel
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.TYPE
     *
     * @return the value of tb_order.TYPE
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.TYPE
     *
     * @param type the value for tb_order.TYPE
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.total_money
     *
     * @return the value of tb_order.total_money
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public Long getTotalMoney() {
        return totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.total_money
     *
     * @param totalMoney the value for tb_order.total_money
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setTotalMoney(Long totalMoney) {
        this.totalMoney = totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.rebate_money
     *
     * @return the value of tb_order.rebate_money
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public Long getRebateMoney() {
        return rebateMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.rebate_money
     *
     * @param rebateMoney the value for tb_order.rebate_money
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setRebateMoney(Long rebateMoney) {
        this.rebateMoney = rebateMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.final_money
     *
     * @return the value of tb_order.final_money
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public Long getFinalMoney() {
        return finalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.final_money
     *
     * @param finalMoney the value for tb_order.final_money
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setFinalMoney(Long finalMoney) {
        this.finalMoney = finalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.state
     *
     * @return the value of tb_order.state
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.state
     *
     * @param state the value for tb_order.state
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.pay_money
     *
     * @return the value of tb_order.pay_money
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public Long getPayMoney() {
        return payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.pay_money
     *
     * @param payMoney the value for tb_order.pay_money
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setPayMoney(Long payMoney) {
        this.payMoney = payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.pay_state
     *
     * @return the value of tb_order.pay_state
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public Integer getPayState() {
        return payState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.pay_state
     *
     * @param payState the value for tb_order.pay_state
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setPayState(Integer payState) {
        this.payState = payState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.pay_type
     *
     * @return the value of tb_order.pay_type
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.pay_type
     *
     * @param payType the value for tb_order.pay_type
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.pay_id
     *
     * @return the value of tb_order.pay_id
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public Long getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.pay_id
     *
     * @param payId the value for tb_order.pay_id
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setPayId(Long payId) {
        this.payId = payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.cancel_type
     *
     * @return the value of tb_order.cancel_type
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public Integer getCancelType() {
        return cancelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.cancel_type
     *
     * @param cancelType the value for tb_order.cancel_type
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setCancelType(Integer cancelType) {
        this.cancelType = cancelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.consignee
     *
     * @return the value of tb_order.consignee
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.consignee
     *
     * @param consignee the value for tb_order.consignee
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.address
     *
     * @return the value of tb_order.address
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.address
     *
     * @param address the value for tb_order.address
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.delivery_start_date
     *
     * @return the value of tb_order.delivery_start_date
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    @JsonFormat(pattern = "HH:mm",timezone="GMT+8")
    public Date getDeliveryStartDate() {
        return deliveryStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.delivery_start_date
     *
     * @param deliveryStartDate the value for tb_order.delivery_start_date
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setDeliveryStartDate(Date deliveryStartDate) {
        this.deliveryStartDate = deliveryStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.delivery_end_date
     *
     * @return the value of tb_order.delivery_end_date
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    @JsonFormat(pattern = "HH:mm",timezone="GMT+8")
    public Date getDeliveryEndDate() {
        return deliveryEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.delivery_end_date
     *
     * @param deliveryEndDate the value for tb_order.delivery_end_date
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setDeliveryEndDate(Date deliveryEndDate) {
        this.deliveryEndDate = deliveryEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.create_user
     *
     * @return the value of tb_order.create_user
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.create_user
     *
     * @param createUser the value for tb_order.create_user
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.create_user_mobile
     *
     * @return the value of tb_order.create_user_mobile
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public String getCreateUserMobile() {
        return createUserMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.create_user_mobile
     *
     * @param createUserMobile the value for tb_order.create_user_mobile
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setCreateUserMobile(String createUserMobile) {
        this.createUserMobile = createUserMobile == null ? null : createUserMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.mobile
     *
     * @return the value of tb_order.mobile
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.mobile
     *
     * @param mobile the value for tb_order.mobile
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.remark
     *
     * @return the value of tb_order.remark
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.remark
     *
     * @param remark the value for tb_order.remark
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.unnormal_desc
     *
     * @return the value of tb_order.unnormal_desc
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public String getUnnormalDesc() {
        return unnormalDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.unnormal_desc
     *
     * @param unnormalDesc the value for tb_order.unnormal_desc
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setUnnormalDesc(String unnormalDesc) {
        this.unnormalDesc = unnormalDesc == null ? null : unnormalDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.create_date
     *
     * @return the value of tb_order.create_date
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.create_date
     *
     * @param createDate the value for tb_order.create_date
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.update_user
     *
     * @return the value of tb_order.update_user
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.update_user
     *
     * @param updateUser the value for tb_order.update_user
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.update_date
     *
     * @return the value of tb_order.update_date
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.update_date
     *
     * @param updateDate the value for tb_order.update_date
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.sex
     *
     * @return the value of tb_order.sex
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.sex
     *
     * @param sex the value for tb_order.sex
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.pay_mode
     *
     * @return the value of tb_order.pay_mode
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public Integer getPayMode() {
        return payMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.pay_mode
     *
     * @param payMode the value for tb_order.pay_mode
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setPayMode(Integer payMode) {
        this.payMode = payMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.lock_state
     *
     * @return the value of tb_order.lock_state
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public Integer getLockState() {
        return lockState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.lock_state
     *
     * @param lockState the value for tb_order.lock_state
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setLockState(Integer lockState) {
        this.lockState = lockState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.trader
     *
     * @return the value of tb_order.trader
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public String getTrader() {
        return trader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.trader
     *
     * @param trader the value for tb_order.trader
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setTrader(String trader) {
        this.trader = trader == null ? null : trader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.trader_name
     *
     * @return the value of tb_order.trader_name
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public String getTraderName() {
        return traderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.trader_name
     *
     * @param traderName the value for tb_order.trader_name
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setTraderName(String traderName) {
        this.traderName = traderName == null ? null : traderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.trader_sex
     *
     * @return the value of tb_order.trader_sex
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public String getTraderSex() {
        return traderSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.trader_sex
     *
     * @param traderSex the value for tb_order.trader_sex
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setTraderSex(String traderSex) {
        this.traderSex = traderSex == null ? null : traderSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.trader_mobile
     *
     * @return the value of tb_order.trader_mobile
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public String getTraderMobile() {
        return traderMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.trader_mobile
     *
     * @param traderMobile the value for tb_order.trader_mobile
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setTraderMobile(String traderMobile) {
        this.traderMobile = traderMobile == null ? null : traderMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.trader_address
     *
     * @return the value of tb_order.trader_address
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public String getTraderAddress() {
        return traderAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.trader_address
     *
     * @param traderAddress the value for tb_order.trader_address
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setTraderAddress(String traderAddress) {
        this.traderAddress = traderAddress == null ? null : traderAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.winner
     *
     * @return the value of tb_order.winner
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public Long getWinner() {
        return winner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.winner
     *
     * @param winner the value for tb_order.winner
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setWinner(Long winner) {
        this.winner = winner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.winner_remark
     *
     * @return the value of tb_order.winner_remark
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public String getWinnerRemark() {
        return winnerRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.winner_remark
     *
     * @param winnerRemark the value for tb_order.winner_remark
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setWinnerRemark(String winnerRemark) {
        this.winnerRemark = winnerRemark == null ? null : winnerRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.college_id
     *
     * @return the value of tb_order.college_id
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public Long getCollegeId() {
        return collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.college_id
     *
     * @param collegeId the value for tb_order.college_id
     *
     * @mbggenerated Mon Oct 10 16:41:30 CST 2016
     */
    public void setCollegeId(Long collegeId) {
        this.collegeId = collegeId;
    }

    public String getCollegeName() {
        return collegeName;
    }

    public void setCollegeName(String collegeName) {
        this.collegeName = collegeName;
    }

    public String getWinnerMobile() {
        return winnerMobile;
    }

    public void setWinnerMobile(String winnerMobile) {
        this.winnerMobile = winnerMobile;
    }

    public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public List<OrderFlowBean> getOrderFlowList() {
        return orderFlowList;
    }

    public void setOrderFlowList(List<OrderFlowBean> orderFlowList) {
        this.orderFlowList = orderFlowList;
    }

    public String getWaybillNo() {
        return waybillNo;
    }

    public void setWaybillNo(String waybillNo) {
        this.waybillNo = waybillNo;
    }

    public String getPickUpCode() {
        return pickUpCode;
    }

    public void setPickUpCode(String pickUpCode) {
        this.pickUpCode = pickUpCode;
    }

    public String getServiceType() {
        return serviceType;
    }

    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }

    public Long getRewardMoney() {
        return rewardMoney;
    }

    public void setRewardMoney(Long rewardMoney) {
        this.rewardMoney = rewardMoney;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getAgentPickupCode() {
        return agentPickupCode;
    }

    public void setAgentPickupCode(String agentPickupCode) {
        this.agentPickupCode = agentPickupCode;
    }
}