package com.rofour.baseball.dao.order.mapper;

import com.rofour.baseball.controller.model.order.OrderManagerQueryParamInfo;
import com.rofour.baseball.controller.model.order.PacketUserQueryParamInfo;
import com.rofour.baseball.dao.order.bean.OrderFlowBean;
import com.rofour.baseball.dao.order.bean.OrderManagerBean;
import com.rofour.baseball.dao.order.bean.OrderManagerBeanExample;
import com.rofour.baseball.dao.user.bean.PacketUserBean;
import org.apache.ibatis.annotations.Param;

import javax.inject.Named;
import java.util.List;

/**
 * 订单管理Mapper
 * @author wangyu
 * @ClassName:com.rofour.baseball.dao.order.mapper.OrderManagerMapper
 * @Description: 描述：
 * @date 2016/10/10 16:17
 */
@Named("orderManagerMapper")
public interface OrderManagerMapper {
	/**
	 * 根据订单ID查询订单流转记录信息
	 * @param orderId 订单编号
	 * @return 订单流转记录列表
	 */
	List<OrderFlowBean> selectOrderFlowByOrderId(Long orderId);
	/**
	 * 获取订单详情
	 * @param orderId 订单ID
	 * @return 订单详情
	 */
	OrderManagerBean selectOrderDetail(Long orderId);
	/**
	 * 查询订单列表
	 * @param queryParamInfo 查询参数对象
	 * @return 订单列表
	 */
	List<OrderManagerBean> selectOrderList(OrderManagerQueryParamInfo queryParamInfo);

	/**
	 * 查询订单数量
	 * @param queryParamInfo 查询参数对象
	 * @return 订单数量
	 */
	int selectOrderListCount(OrderManagerQueryParamInfo queryParamInfo);

	/**
	 * 查询小派列表
	 * @param queryParamInfo 查询小派参数对象
	 * @return 小派列表
	 */
	List<PacketUserBean> selectPacketUserList(PacketUserQueryParamInfo queryParamInfo);
	/**
	 * 查询小派数量
	 * @param queryParamInfo 查询小派参数对象
	 * @return 小派数量
	 */
	int selectPacketUserListCount(PacketUserQueryParamInfo queryParamInfo);
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tb_order
	 *
	 * @mbggenerated Mon Oct 10 16:41:30 CST 2016
	 */
	int countByExample(OrderManagerBeanExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tb_order
	 *
	 * @mbggenerated Mon Oct 10 16:41:30 CST 2016
	 */
	List<OrderManagerBean> selectByExample(OrderManagerBeanExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tb_order
	 *
	 * @mbggenerated Mon Oct 10 16:41:30 CST 2016
	 */
	OrderManagerBean selectByPrimaryKey(Long orderId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tb_order
	 *
	 * @mbggenerated Mon Oct 10 16:41:30 CST 2016
	 */
	int updateByExampleSelective(@Param("record") OrderManagerBean record, @Param("example") OrderManagerBeanExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tb_order
	 *
	 * @mbggenerated Mon Oct 10 16:41:30 CST 2016
	 */
	int updateByPrimaryKeySelective(OrderManagerBean record);
}
