package com.rofour.baseball.dao.activity.bean;

import com.rofour.baseball.controller.model.BasePage;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * Acct activity.
 *
 * @author will
 * @Description
 * @date 2016 -08-16 13:32:49
 */
public class AcctActivity extends BasePage implements Serializable {

    private static final long serialVersionUID = -4675266529071234648L;
    //活动id
    private Integer activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_acct_activity.activity_name
     *
     * @活动名称
     */
    private String activityName;

    public List<Integer> getPolicyIds() {
        return policyIds;
    }

    public void setPolicyIds(List<Integer> policyIds) {
        this.policyIds = policyIds;
    }

    //策略ids
    private List<Integer> policyIds;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_acct_activity.activity_type
     *
     * @mbggenerated
     */
    private Byte activityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_acct_activity.channel_id
     *
     * @mbggenerated
     */
    private Byte channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_acct_activity.province_id
     *
     * @mbggenerated
     */
    private Integer provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_acct_activity.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * Gets start start time.
     *
     * @return the start start time
     */
    public String getStartStartTime() {
        return startStartTime;
    }

    /**
     * Sets start start time.
     *
     * @param startStartTime the start start time
     */
    public void setStartStartTime(String startStartTime) {
        this.startStartTime = startStartTime;
    }

    /**
     * Gets end start time.
     *
     * @return the end start time
     */
    public String getEndStartTime() {
        return endStartTime;
    }

    /**
     * Sets end start time.
     *
     * @param endStartTime the end start time
     */
    public void setEndStartTime(String endStartTime) {
        this.endStartTime = endStartTime;
    }

    private String provinceName;

    /**
     * Gets province name.
     *
     * @return the province name
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * Sets province name.
     *
     * @param provinceName the province name
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    private String startStartTime;
    private String endStartTime;
    //    备注
    private String remark;

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    private Date endTime;

    private Date createTime;

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    private Long putAmount;

    private Integer state;

    /**
     * Gets be deleted.
     *
     * @return the be deleted
     */
    public Integer getBeDeleted() {
        return beDeleted;
    }

    /**
     * Sets be deleted.
     *
     * @param beDeleted the be deleted
     */
    public void setBeDeleted(Integer beDeleted) {
        this.beDeleted = beDeleted;
    }

    /**
     * Gets state.
     *
     * @return the state
     */
    public Integer getState() {
        return state;
    }

    /**
     * Sets state.
     *
     * @param state the state
     */
    public void setState(Integer state) {
        this.state = state;
    }

    private Integer beDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_acct_activity.activity_id
     *
     * @return the value of tb_acct_activity.activity_id
     * @mbggenerated
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_acct_activity.activity_id
     *
     * @param activityId the value for tb_acct_activity.activity_id
     * @mbggenerated
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_acct_activity.activity_name
     *
     * @return the value of tb_acct_activity.activity_name
     * @mbggenerated
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_acct_activity.activity_name
     *
     * @param activityName the value for tb_acct_activity.activity_name
     * @mbggenerated
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_acct_activity.activity_type
     *
     * @return the value of tb_acct_activity.activity_type
     * @mbggenerated
     */
    public Byte getActivityType() {
        return activityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_acct_activity.activity_type
     *
     * @param activityType the value for tb_acct_activity.activity_type
     * @mbggenerated
     */
    public void setActivityType(Byte activityType) {
        this.activityType = activityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_acct_activity.channel_id
     *
     * @return the value of tb_acct_activity.channel_id
     * @mbggenerated
     */
    public Byte getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_acct_activity.channel_id
     *
     * @param channelId the value for tb_acct_activity.channel_id
     * @mbggenerated
     */
    public void setChannelId(Byte channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_acct_activity.province_id
     *
     * @return the value of tb_acct_activity.province_id
     * @mbggenerated
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_acct_activity.province_id
     *
     * @param provinceId the value for tb_acct_activity.province_id
     * @mbggenerated
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_acct_activity.start_time
     *
     * @return the value of tb_acct_activity.start_time
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_acct_activity.start_time
     *
     * @param startTime the value for tb_acct_activity.start_time
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }


    /**
     * Gets end time.
     *
     * @return the end time
     */
    public Date getEndTime() {
        return endTime;
    }


    /**
     * Sets end time.
     *
     * @param endTime the end time
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }


    /**
     * Gets put amount.
     *
     * @return the put amount
     */
    public Long getPutAmount() {
        return putAmount;
    }


    /**
     * Sets put amount.
     *
     * @param putAmount the put amount
     */
    public void setPutAmount(Long putAmount) {
        this.putAmount = putAmount;
    }

    /**
     * Gets contacts.
     *
     * @return the contacts
     */
    public List<AcctActivityPolicyBean> getContacts() {
        return contacts;
    }

    /**
     * Sets contacts.
     *
     * @param contacts the contacts
     */
    public void setContacts(List<AcctActivityPolicyBean> contacts) {
        this.contacts = contacts;
    }

    //策略
    private List<AcctActivityPolicyBean> contacts;
}