package com.zhiduan.axp.dao.activity.mapper;

import com.zhiduan.axp.dao.activity.bean.AcctActivity;

import javax.inject.Named;
import java.util.List;

@Named("acctActivityMapper")
public interface AcctActivityMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_acct_activity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer activityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_acct_activity
     *
     * @mbggenerated
     */
    int insert(AcctActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_acct_activity
     *
     * @mbggenerated
     */
    int insertSelective(AcctActivity record);

    List<AcctActivity> getAll(AcctActivity record);

    int selectAllCount(AcctActivity record);
    int selectIsExtisNameCount(AcctActivity record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_acct_activity
     *
     * @mbggenerated
     */
    AcctActivity selectByPrimaryKey(Integer activityId);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_acct_activity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AcctActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_acct_activity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AcctActivity record);
}